# Generated by Django 5.0.3 on 2024-03-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_comments_count_comment_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
    ]
